### ISSUE TITLE
.

### ISSUE THREAD

**Issue by LNLenost** [kandowontu/yoshis-island-fastrom#1]
Hey Kando, I saw i got banned from the repo and I'm not able to play the game anymore. I wont blame u, I perfectly know im annoying asf and also irritating.
I wrote this message just to tell you something. You dont have to read it though if u dont want to.

At school I have no friends. While all my classmates have lunch together, I spend time online.
When i saw the GBATemp article about Famidash, I thought this was the opportunity to make some new friends while doing what I love: playing games and programming.

The day you approved the PR with my name in the readme, I cried because of how I was happy. I was in a group. I helped others. I sent the readme screenshot to at least 20 people because I was proud of myself.
But then I went too far. When I wrote the comments on yt I really thought I was part of the team. But I wasn't.

With that said, I'm going to play the only nightly I can play, the one on my SD Card.
Sorry for wasting your time, and congrats for the amazing work you and your team has made.
Wish you the best.

LNLenost

**Comment by kandowontu** [comment]
Listen, we're all human and we make mistakes. You have to understand our dilemma though, that in order to project an image of being involved with the community and being able to show up as the actual developers to say hi is something that your youtube comments stripped us the ability of doing.

Its almost like you took the wind out of our sails.

I am willing to unban you, and even (in the near future) add you into an additional credits section of the site for your bug reporting.

But please, a) use discussion for questions/comments/realizations and b) only use bug reports properly for actual issues.

We also ask that you please refrain from publically misrepresenting yourself as a developer of the game. If you want to call yourself a 'beta tester', thats absolutely fine.

We do appreciate your help, and we absolutely understand the desire to want to be a part of something this big. Unforunately the way you went about it was a bit wrong. We can all learn from our mistakes, and I hope this is one that helps you further in your life.

I am removing the ban, and we welcome you back to enjoy the project once again.

**Comment by LNLenost** [comment]
Ok, I understand your point and I'm sorry for creating this dilemma. Thanks
for your comprehension :D
